import type { Metadata } from "next";
import "./globals.css";
import HeaderElement from "@/components/HeaderElement";

export const metadata: Metadata = {
  title: "Style32 - мода в вещах",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=""
      >
        {children}
      </body>
    </html>
  );
}
